app/models/bot.py
import os

from .commons import db, build_fk

AUDIO_FOLDER = 'audio'


class Bot(db.Model):
    id = db.Column(db.Integer, primary_key=True)

    campaign_id, campaign = build_fk('campaign.id', 'Campaign', 'bots', unique=True)
    audio_channel = db.Column(db.Integer, nullable=True)
    _volume = db.Column(db.Float, nullable=False, default=1)
    # My Discord tokens have 59 chars, I'm assuming all of them do
    token = db.Column(db.String(60), unique=True, nullable=False)
    prefix = db.Column(db.String(3), default="!")

    def __repr__(self):
        return '<Bot {}>'.format(self.campaign.name)

    def send(self, message):
        from app.discord_bot import manager
        manager.send_msg(self, message, self.audio_channel)

    def _audio_folder(self):
        return os.path.join(AUDIO_FOLDER, str(self.campaign_id))

    def get_audio_files(self):
        audio_files = {}
        audio_folder = self._audio_folder()
        for category in os.scandir(audio_folder):
            if not category.is_dir():
                from colors import cprint
                cprint("Ignoring {}. Only folders inside {} are considered".format(
                    category.name, audio_folder), color='red')
                continue

            category_dict = {}
            for audio in os.scandir(category):
                name = os.path.splitext(audio.name)[0]
                category_dict[name] = audio.path
            audio_files[category.name] = category_dict
        return audio_files

    def play(self, category, file):
        from app.discord_bot import manager
        audio_files = self.get_audio_files()
        if category not in audio_files:
            return False
        category_dict = audio_files[category]
        if file not in category_dict:
            return False
        file_path = category_dict[file]
        manager.play_audio(self, file_path, self.audio_channel)

    def pause(self):
        from app.discord_bot import manager
        manager.toggle_pause_audio(self, self.audio_channel)

    def stop(self):
        from app.discord_bot import manager
        manager.stop_audio(self, self.audio_channel)

    @property
    def volume(self):
        return self._volume

    @volume.setter
    def volume(self, value):
        from app.discord_bot import manager
        # Ensure 0-1 range
        value = max(min(value, 1), 0)
        self._volume = value
        manager.volume_audio(self, self.audio_channel, value)

        try:
            db.session.add(self)
            db.session.commit()
        except Exception as e:
            from colors import cprint
            cprint(e, color='red')
        return self._volume

app/models/campaign.py
from .commons import db, build_fk


class Campaign(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False)
    system = db.Column(db.String(20), nullable=False, default='generic')
    description = db.Column(db.Text, nullable=True)
    allow_player_edit = db.Column(db.Boolean, default=False, nullable=False,
                                  info={'label': 'Allow player to edit characters'})
    gm_id, gm = build_fk('player.id', 'Player', 'narrating')

    def __repr__(self):
        return '<Campaign {}>'.format(self.name)

    def is_valid(self):
        from app.system import manager
        return self.system in manager.systems

    @property
    def system_long(self):
        from app.system import manager
        # Default to the value stored as system if we don't know it
        system_long = self.system
        if self.system in manager.systems:
            system_long = manager.systems[self.system].long_name
        return system_long

    @property
    def players(self):
        return [c.player for c in self.characters if c.player is not None]

    def get_character(self, player):
        from app.models import Character
        return Character.query.filter_by(campaign=self, player=player).first()

    @property
    def as_dict(self):
        """

        :return: Object data in serializable format
        """
        
        return {
            'id': self.id,
            'name': self.name,
            'system': self.system,
            'system_long': self.system_long,
            'description': self.description,
            'allow_player_edit': self.allow_player_edit,
            'gm_id': self.gm_id
        }

app/views/commons.py
from flask_security.utils import hash_password
from flask_security.views import logout
from flask_wtf import FlaskForm
from flask import Blueprint, render_template, redirect, request, url_for
from flask_login import login_required, current_user
from wtforms import SelectField, StringField, TextAreaField, validators

from app.models import Campaign, Player
from app.system import manager


bp = Blueprint('main', __name__)


def campaign_url(campaign):
    from app.system import manager
    return '/'.join([manager.get_base_url(campaign.system), str(campaign.id)])


@bp.context_processor
def inject_campaign_url():
    return {
        'campaign_url': campaign_url
    }


@bp.route('/')
@login_required
def index():
    return render_template('index.html')


@bp.route('/campaign/new', methods=('GET', 'POST'))
@login_required
def new_campaign():
    from app.models import db
    from app.views import CampaignForm

    form = CampaignForm()
    form.system.choices = [(s, s) for s in manager.systems]
    if form.validate_on_submit():
        campaign = Campaign(name=form.name.data,
                            description=form.description.data,
                            system=form.system.data,
                            gm=current_user
                            )
        try:
            db.session.add(campaign)
            db.session.commit()
        except Exception as e:
            form.errors['SQL'] = [str(e)]
        else:
            return redirect(campaign_url(campaign))

    return render_template('edit_campaign.html', form=form, href=url_for('main.new_campaign'))


@bp.route('/campaign/<campaign:campaign>', methods=('GET', 'POST'))
@login_required
def campaign(campaign):
    from app.models import db
    from app.views import CampaignForm

    if not campaign or campaign.gm != current_user:
        generic_error = "Only the GM can edit the campaign"
        return render_template("base/error.html", campaign=None, errors=[generic_error]), 400

    form = CampaignForm(obj=campaign)
    # Cannot modify system once created
    form.system.choices = [(campaign.system, campaign.system)]
    if form.validate_on_submit():
        form.populate_obj(campaign)
        try:
            db.session.add(campaign)
            db.session.commit()
        except Exception as e:
            form.errors['SQL'] = [str(e)]
        else:
            return redirect(campaign_url(campaign))

    return render_template('edit_campaign.html', form=form, href=url_for('main.campaign', campaign=campaign))


@bp.route('/campaign/<campaign:campaign>/del')
@login_required
def del_campaign(campaign):
    if not campaign or campaign.gm != current_user:
        generic_error = "Only the GM can delete the campaign"
        return render_template("base/error.html", campaign=None, errors=[generic_error]), 400

    try:
        from app.models import db
        db.session.delete(campaign)
        db.session.commit()
    except Exception as e:
        db.rollback()
        from colors import cprint
        cprint(e, color='red')
        return render_template("base/error.html", campaign=campaign, errors=[str(e)]), 400

    return redirect(url_for('main.index'))


@bp.route('/settings', methods=('GET', 'POST'))
@login_required
def settings():
    from app.views.model_forms import PlayerSettingsForm
    from flask_security.forms import ChangePasswordForm
    from app.models import db

    user_form = PlayerSettingsForm(obj=current_user)
    change_password_form = ChangePasswordForm()

    if request.form:
        # We have a hidden field to say which form is submitted
        submitted_form = request.form['submitted_form']

        if submitted_form == 'general':
            if user_form.validate_on_submit():
                if not user_form.email.data:
                    user_form.email.data = None
                user_form.populate_obj(current_user)
                try:
                    db.session.add(current_user)
                    db.session.commit()
                except Exception as e:
                    # TODO parse the error better
                    print(e)
                    db.session.rollback()

        elif submitted_form == 'change_password':
            if change_password_form.validate_on_submit():
                print("Validated change password")
                new_password = change_password_form.new_password.data
                current_user.password = hash_password(new_password)
                try:
                    db.session.add(current_user)
                    db.session.commit()
                except Exception as e:
                    # TODO parse the error better
                    print(e)
                    db.session.rollback()

    return render_template('settings/settings.html', user_form=user_form, change_password_form=change_password_form)


@bp.route('/del_my_acc')
@login_required
def del_my_acc():
    delete_user(current_user)
    logout()
    return redirect(url_for('security.login'))


def delete_user(user):
    """
    Helper function to delete a user.
    Only admins can delete anyone else, but a regular user should only call this to delete his own account.

    It should be impossible for a regular user to call this with anything other than current_user,
    but as a safeguard if a non-admin user tries to call this delete his account independent of parameter.
    :param user:
    :return:
    """
    from app.models import db

    if not current_user.has_role('admin'):
        user = current_user
    elif user is None:
        return "Could not find specified user"

    db.session.delete(user)
    db.session.commit()
    return None


@bp.route('/players')
@login_required
def list_players():
    like = request.args.get('like')
    if like is None:
        like = '%'
    players = Player.query.filter(Player.name.like(like)).all()
    return {'players': [p.name for p in players]}

app/templates/bot.html
{% extends "base/base.html" %}

{% from "base/macros.html" import elements_list %}

{% block content %}

{{ elements_list(elements, title=audio_title) }}

<script>
    function play_music(category, value){
        $.post("{{play_url}}", {'category': category, 'audio': value});
    }
</script>

{% endblock %}

app/templates/campaign.html
{% extends "base/base.html" %}

{% block title %}
{{campaign.name}}
{% endblock %}

{% block content %}
  <h2>Overview for {{campaign.name}}</h2>

<br>

{% if current_user == campaign.gm %}

{# TODO See Issue #21
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#getTokenModal">
 <i class="fa fa-share-alt"></i>
</button>
Get Character Share

<!-- Modal -->
<div class="modal fade" id="getTokenModal" tabindex="-1" role="dialog" aria-labelledby="getTokenModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="getTokenModalLabel">How would you like to get the link</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Player: {{player_form.player_id}}
        <br>
        Select the method of delivery of the link
      </div>
      <div class="modal-footer">

        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="disabled btn btn-primary">
          <!-- data-dismiss="modal" onclick="send_token_via_mail();"> -->

          <i class="fa fa-envelope"></i>
            E-Mail
        </button>
        <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="copy_token();">
          <i class="fa fa-clone"></i>
          Copy to clipboard
        </button>
          <button type="button" class="disabled btn btn-primary">
             <!-- data-dismiss="modal" onclick="send_token_via_discord();"> -->
            Discord
          </button>

      </div>
    </div>
  </div>
</div>
#}

{{ campaign.description }}

{% endif %}

{% endblock %}

{% block scripts %}
  {{super()}}
<script src="/static/get_token.js"></script>
{% endblock scripts%}

app/templates/edit_campaign.html
{% extends "base/base.html" %}

{% from "base/macros.html" import form_errors %}
{% from "base/settings_macros.html" import bool_setting %}

{% block content %}

 <form id="campaign_form" method="POST" action="{{href}}">
   {{ form.csrf_token }}

   {{ form_errors(form) }}

<div class="row">
  <div class="col-2">
    System: {{ form.system }}
  </div>
  <div class="col-10">
    {{ form.name(style="width: 100%;", placeholder="Campaign name") }}
  </div>
</div>
     <br>
     {{ bool_setting(form.allow_player_edit) }}
     {{ form.description(placeholder="Campaign Description") }}
 </form>


{% endblock %}


{% block footer %}

{# Using form reference outside of the form is HTML5, maybe not all browsers support it #}
<button form="campaign_form" class="btn btn-lg btn-success btn-block" type="submit">
  Save
</button>
{% endblock footer %}

app/templates/index.html
{% extends "base/base.html" %}  

{% from "base/macros.html" import campaign_color with context %}
{% from "base/macros.html" import del_btn %}

{% block title %} 
  Index 
{% endblock %} 

{% block content %} 

  <div class="card-columns"> 

    {% for c in current_user.campaigns %}
      <div class="card text-center {{campaign_color(c, 'border')}}">

        <div class="card-body"> 
          <h5 class="card-title">{{c.name}}</h5> 
          <p class="card-text">{{c.description}}</p> 
          <a href="{{ campaign_url(c)}}" class="btn btn-block {{campaign_color(c)}}">Select</a>
        </div> 
        
        <div class="card-footer text-muted">
          {% if c and c.gm == current_user %}
            <div class="row">
              <div class="col-2">
                <a class="btn btn-primary float-right"
                        href="{{url_for('main.campaign', campaign=c)}}">
                  <i class="fa fa-edit"></i>
                </a>
              </div>
              <div class="col-8">
                {{c.system_long}}
              </div>
            <div class="col-2">
              {{del_btn( url_for('main.del_campaign', campaign=c),
                         msg="Are you sure you wish to delete campaign \"{}\"?".format(c.name) ) }}
            </div>
          {% else %}
            {{c.system_long}}
          {% endif %}
          </div>

        </div> 
      </div> 
    {% endfor %} 
    
  </div> 
  


{% endblock %}   

{% from "base/macros.html" import new_btn %}
{% block footer %}
  {{ new_btn("Campaign", url_for('main.new_campaign') )}}
{% endblock footer %}

app/templates/session.html
{% extends "base/base.html" %}

{% block content %}
  <h2>Sessions of {{campaign.name}}</h2>
{% endblock %}

{% from "base/macros.html" import new_btn %}
{% block footer %}
 {# {{ new_btn("Session") }} #}
{% endblock footer %}